# Generated by Django 4.1 on 2022-11-03 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user_group", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("amount", models.FloatField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_group.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionDetails",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "shareType",
                    models.IntegerField(
                        choices=[(1, "PERCENT"), (2, "ABSOLUTE")], default=1
                    ),
                ),
                ("shareValue", models.FloatField()),
                (
                    "transactionID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transaction.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="user_group.user",
                    ),
                ),
            ],
        ),
    ]
