# Generated by Django 4.1 on 2022-11-03 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_group", "0001_initial"),
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TransactionDetails", new_name="TransactionDetail",
        ),
    ]
